[colors.primary]
background = "#1e1b13"
foreground = "#e9e2d4"

[colors.cursor]
cursor = "#dfc56d"
text = "#1e1b13"

[colors.selection]
background = "#564500"
text = "#fde186"

[colors.normal]
black   = "#979080"
red     = "#ffb4ab"
green   = "#abd0b0"
yellow  = "#d3c6a1"
blue    = "#dfc56d"
magenta = "#2e4e36"
cyan    = "#4f462a"
white   = "#e9e2d4"

[colors.bright]
black   = "#4b4639"
red     = "#ffb4ab"
green   = "#abd0b0"
yellow  = "#dfc56d"
blue    = "#d3c6a1"
magenta = "#564500"
cyan    = "#4f462a"
white   = "#ffffff"
