font=Noto Sans 11
background-color={{colors.surface_container_high.default.hex}}
text-color={{colors.on_surface.default.hex}}
border-color={{colors.primary.default.hex}}
border-size=2
border-radius=10
padding=12
margin=14
default-timeout=6000
icon-location=left
max-visible=4

[mode=dnd]
invisible=1
