background            #1e1b13
foreground            #e9e2d4
cursor                #dfc56d
cursor_text_color     #1e1b13
selection_background  #564500
selection_foreground  #fde186

color0  #979080
color1  #ffb4ab
color2  #abd0b0
color3  #d3c6a1
color4  #dfc56d
color5  #2e4e36
color6  #4f462a
color7  #e9e2d4

color8  #4b4639
color9  #ffb4ab
color10 #abd0b0
color11 #dfc56d
color12 #d3c6a1
color13 #564500
color14 #4f462a
color15 #ffffff

active_tab_foreground   #1e1b13
active_tab_background   #dfc56d
inactive_tab_foreground #d3c6a1
inactive_tab_background #4f462a
tab_bar_background      #1e1b13
